### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zeule** [Davide-sd/ip_address#3]
Can't install using cmake:
```
CMake Error at cmake_install.cmake:49 (file):
  file INSTALL cannot find
  "/var/portage/tmp/portage/kde-plasma/plasma-applet-public-ip-9999/work/plasma-applet-public-ip-9999/plasmoid/metadata.desktop".
```

**Comment by DanaHolt** [comment]
I just submitted a pull request to add the missing .desktop file:
https://github.com/Davide-sd/ip_address/pull/4

**Comment by Davide-sd** [comment]
Sorry for the long wait.... The metadata.desktop has been added, thanks @DanaHolt .
I'm closing this issue.
