### ISSUE TITLE
IP address in panel

### ISSUE THREAD

**Issue by wizonesolutions** [Davide-sd/ip_address#5]
I have a widescreen monitor and plenty of space I could use on the bottom panel. Would it be possible to add an option to show the current IP address in the panel itself?

Thanks for publishing the add-on.

**Comment by Davide-sd** [comment]
I'll look into it next week! :)

**Comment by Davide-sd** [comment]
Sorry for the late, I've implemented it! Thank you for the suggestion! :)

**Comment by wizonesolutions** [comment]
Great, can't wait for it to release! Thanks!
