### ISSUE TITLE
Respond to network change

### ISSUE THREAD

**Issue by wizonesolutions** [Davide-sd/ip_address#6]
Me again :)

I was wondering if it is possible to have the widget detect and respond to network changes somehow? Or even just a way to send a message to it through the CLI to tell it to update immediately? I mostly use this to ensure that my WireGuard VPN connection is working properly, but I can only set the refresh interval to 1 minute at the shortest. Any suggestions?

**Comment by Davide-sd** [comment]
I did look into it when I implemented this plugin, but given the lack of documentation on KDE side and the little time at my disposal, I ended up not pursuing that feature. 

There should be a hidden feature though: whenever you are in doubt, middle click over the widget and it should send a request to ipinfo to update the visualized IP address.

Let me know if this was somehow helpful.

**Comment by akwala** [comment]
> There should be a hidden feature though: whenever you are in doubt, middle click over the widget and it should send a request to ipinfo to update the visualized IP address.

Thanks!
