### ISSUE TITLE
QML QQuickText: Anchors on an item that is managed by a layout

### ISSUE THREAD

**Issue by RogueScholar** [Davide-sd/ip_address#8]
This has no effect on the widget's functionality (splendid job on that, BTW) but Lordy is my ~/.xsession-errors file bloated with the following:

```qml
$XDG_DATA_HOME/plasma/plasmoids/com.github.davide-sd.ipaddress
    /contents/ui/FullRepresentation.qml:156:13:
QML QQuickText: Detected anchors on an item that is managed by a layout.
    This is undefined behavior; use Layout.alignment instead.
```
I believe it's pretty simple to fix, but _nobody_ should take my advice on writing QML... I always start off feeling like I understand how to accomplish what I want to do and usually end up conceding some measure of defeat a few hours later with something that technically works,...but with none of the elegance I envisioned at the start. My approach was to swap out `anchors.horizontalCenter: parent.horizontalCenter` [here](https://github.com/Davide-sd/ip_address/blob/dd7213ba32c297c25b66d98433416d310b9e68ae/plasmoid/contents/ui/FullRepresentation.qml#L158) with `Layout.alignment: Qt.AlignHCenter` and as yet nothing seems to have caught fire. :man_shrugging: 

Thanks again for the nifty desktop tchotchke. :+1:

**Comment by Davide-sd** [comment]
Thank you! I will take a look next month to see what I can do about, unfortunately I'm not really familiar with QML, but I'll figure it out!

**Comment by Davide-sd** [comment]
This should be fixed now... Thanks for letting me know about it :)
