### ISSUE TITLE
Doesn't work with Wireguard

### ISSUE THREAD

**Issue by Privacy-Badger-User** [Davide-sd/ip_address#9]
The subject line tells the story.  I just configured a few WireGuard VPN connections.  The widget understood the change to the first one, but refused to change the flag or the Public IP address as I switched to other Wireguard and, later, standard openVPN connections.  I had to reboot to make things right.  

On reboot, it does function normally ... at least with openVPN!

Thanks for your work on this widget!

**Comment by Davide-sd** [comment]
This widget doesn't actively look for IP changes. Instead, it send a request to IPInfo every X minutes (depending on your settings). If you switch network, it may take up to X minutes to refresh the data! 

Workaround: as soon as you change network, middle click on the widget, it will send a request to update the data.

Definitely need to go back to the code and see if there is a way to trigger an update as soon as an address change is detected by the OS.

**Comment by Privacy-Badger-User** [comment]
Thanks for your response.  Your tips worked for me, although I could only reliably fake a middle click on my two button mouse by tapping the scroll wheel.   A great widget!
